development:
  server: "http://localhost:9292/faye"
  secret_token: "something_safe_and_long"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
